#spring.application.name=ecom-application
#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:ecomdb
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=create
#management.endpoints.web.exposure.include=*
spring:
  application:
    name: ecom-application
  datasource:
    url: jdbc:postgresql://localhost:5432/ecomdb
    username: root
    password: root
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

# For H2 Database configuration, uncomment the following lines:
#  h2:
#    console:
#      enabled: true
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create
#  datasource:
#    url: jdbc:h2:mem:test
#    username: sa
#    password: ''


management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    shutdown:
      access: unrestricted
  info:
    env:
      enabled: true


server:
  shutdown: graceful

info:
  app:
    name: E-Commerce Application
    description: This is a sample e-commerce application built with Spring Boot.
    version: 1.0.0
