spring:
  application:
    name: Provider-Service

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8761/eureka"
    register-with-eureka: true
    fetch-registry: true