spring:
  application:
    name: pure-client
  security:
    oauth2:
      client:
        registration:
          keycloak-client:
            client-id: oauth2-client-credentials
            client-secret: NlcRgsgkPfWLGp9DIOVW0FiSjReARGv1
            authorization-grant-type: client_credentials
            redirect-uri:
            scope:
              - openid
        provider:
          keycloak-client:
            token-uri: http://localhost:8443/realms/oauth2-demos/protocol/openid-connect/token

service2:
  url: http://localhost:8082

server:
  port: 8081
