spring:
  application:
    name: auth-code-flow
  security:
    oauth2:
      client:
        registration:
          oauth2-authorization-code-flow:
            client-id: oauth2-authorization-code-flow
            client-secret: ymySf7vAJ6lTeZU7jQtblwHlctuvdRy5
            scope: openid,profile,email,roles
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/oauth2-authorization-code-flow

        provider:
          oauth2-authorization-code-flow:
            issuer-uri: http://localhost:8443/realms/oauth2-demos
logging:
  level:
    org:
      springframework:
        security:
          oauth2: DEBUG
